### ISSUE TITLE
Set up user and club model

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/pinpoint#12]
Create a user class that will define our users and clubs, probably in a new package `model` within `core`

**Comment by bobheadxi** [comment]
We need to decide how our entities relate to each other

**Comment by srijonsaha** [comment]
Since users and clubs will have a many to many relationship (i.e. each user can be in multiple clubs and each club can have multiple users), I did some research on best ways to represent this relation in NoSQL databases. Here's the options we can potentially use:

1. Have two tables, one for users and one for clubs. Each club would have an attribute that is an array of primary key references to all the users of the club. And each user would have an attribute that is an array of primary key references to all the clubs that user is part of. e.g.
```
{
  { userID: 'Tim',
     ...,
     clubs: ['1837', '3737', '9825', '1847'] 
  },
  { userID: 'Sam',
     ...,
     clubs: ['4323', '1847'] 
  },
  ...
}
```
```
{
  { clubID: '1847',
     ...,
     users: ['Tim', 'Sam'] 
  },
  ...
}
```
The advantage is that we can quickly find out all the people in a club and find out the clubs of a user in a single query. Disadvantage is that DynamoDB has a limit of 400KB per item in a table, so if a lot of users are a part of the club or a user joins lots of clubs, the array of references could get really big and exceed the limit.

2. Have three tables, one for users and one for clubs and one for mapping user to club. e.g.
```
{
  { userID: 'Tim',
     ...,
  },
  { userID: 'Sam',
     ...,
  },
  ...
}
```
```
{
  { clubID: '1847',
     ...,
  },
  ...
}
```
 ```
{
  { userID: 'Tim',
     clubID: '1847'
  },
  { userID: 'Sam',
     clubID: '1847'
  },
  ...
}
```
The big advantage of this option is that we wouldn't have to worry about exceeding item size limit. And this is the standard way of representing many to many relationships in relational databases. But since DynamoDB has no concept of foreign keys we have to manually manage the mapping table to be updated every time updates/deletes happen. The approach would also require multiple queries for getting data such as how many users are part of a club, so there's increased time for common queries.

3. Have a single table for both clubs & users. This would the true NoSQL approach and is listed as best practice for managing many to many relationships in [DyanmoDB docs as Adjacency List Design Pattern](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-adjacency-graphs.html). Here's how the table would look like (userID would be partition key and otherID sort key):
 ```
{
  { userID: 'Tim',
     otherID: 'Tim',
     password: ...,
     name: ....
  },
  { userID: 'Tim',
     otherID: '1847'
     clubName: Launchpad,
     clubDescription: ....
  },
  { userID: 'Tim',
     otherID: '1928',
     clubName: nwHacks,
     clubDescription: ....
  },
  { userID: 'Sam',
     otherID: 'Sam',
     password: ...,
     name: ....
  },
  { userID: 'Sam',
     otherID: '1928'
     clubName: nwHacks,
     clubDescription: ....
  }
}
```
 And to lookup things by club, we would need to build a secondary index on 'otherID':

| otherID (partition key)  | userID  |
|------------------------|--------|
| Tim  | Tim  |
| 1847  | Tim  |
| 1928  | Tim  |
| Sam  | Sam  |
| 1928  | Sam  |

The main advantage of is that it fully takes advantage of what DynamoDB offers. DynamoDB doesn't have a table size limit so we don't care about space. This design will make our queries the fastest. The problem with this design is that it's a shitty way to represent our data, there's a lot of repetition and redundancy.

**Comment by bobheadxi** [comment]
Also interesting, from the [docs about NoSQL design in general](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-general-nosql-design.html):

> NoSQL design is different: 
> - For DynamoDB, by contrast, you shouldn't start designing your schema until you know the questions it will need to answer. Understanding the business problems and the application use cases up front is essential.
> - **You should maintain as few tables as possible in a DynamoDB application. Most well designed applications require only one table.**

More:

> Keep related data together.   Research on routing-table optimization 20 years ago found that "locality of reference" was the single most important factor in speeding up response time: keeping related data together in one place. This is equally true in NoSQL systems today, where keeping related data in close proximity has a major impact on cost and performance. Instead of distributing related data items across multiple tables, you should keep related items in your NoSQL system as close together as possible.... A single table with inverted indexes can usually enable simple queries to create and retrieve the complex hierarchical data structures required by your application.

Continued:

> Use sort order.   Related items can be grouped together and queried efficiently if their key design causes them to sort together.... you should design data keys to distribute traffic evenly across partitions as much as possible, avoiding "hot spots."

And secondary indexes - this might be the `otherID` @srijonsaha brought up in his example:

> Use global secondary indexes.   By creating specific global secondary indexes, you can enable different queries than your main table can support, and that are still fast and relatively inexpensive.

Looks like this is a lot less straight-forward than I had expected - it certainly seems like a single-table solution is the right way to go, given the strong wording here. We do need to be careful about how this might tie into #28, #13. I feel `events` is one of the cases where we might want a new table - it has a very specific access pattern, and most users (ie people accessing forms) will *only* access `events` on read. I might be wrong here though.

I also find the emphasis on key distribution interesting, though I'm not sure how we can account for that.

**Comment by bobheadxi** [comment]
@srijonsaha perhaps try an implementation of option 3 - I am be interested in how this might look programmatically

**Comment by srijonsaha** [comment]
So I misunderstood the Adjacency List Design design recommended by DynamoDB. I took a better look at it and it seems a lot better than I originally thought. With a more fleshed out design, the base table might look like this (the actual ids are prefixed with their type):

| Partition Key | Sort Key  | Other Attributes                               |
|---------------|-----------|------------------------------------------------|
| Club-1234     | Club-1234 | name, description, list of application periods |
| Club-1234     | User-tim  | name, email, role                              |
| Club-1234     | User-sam  | name, email, role                              |
| Club-4321     | Club-4321 | name, description, list of application periods |
| Club-4321     | User-tim  | name, email, role                              |
| User-tim      | User-tim  | name, email, password, other user related info |
| User-sam      | User-sam  | name, email, password, other user related info |

Notice how the club information is only stored once. But the user information is repeated, but this will help our queries. When the user logins/registers we would query on this condition: `partition-key == <userId> & sort-key == <userId>`, this gives us all the user related info. When we are concerned about the user of a specific club, then we can query based on: `partition-key == <clubId> & sort-key == <userId>`. We would only store relevant user info that clubs would need in that item. If we wanted to get all the users info for a specific club we can query on: `partition-key == <clubId> & sort-key BEGINS_WITH "User-"`. 

Now if we wanted to query all clubs that a user is part of, this is where a global secondary index is useful. We could build a secondary index with our base table's sort key and partition key flipped as index's partition key and sort key. e.g.

| Partition Key | Sort Key  | Projected attributes |
|---------------|-----------|----------------------|
| Club-1234     | Club-1234 |                      |
| Club-4321     | Club-4321 |                      |
| User-sam      | Club-1234 | name, role           |
| User-sam      | User-sam  |                      |
| User-tim      | Club-1234 | name, role           |
| User-tim      | Club-4321 | name, role           |
| User-tim      | User-tim  |                      |

The projected attributes are non key attributes we want to include from the base table in index. Advantage of using a index is that they are rebuilt/updated automatically and much more efficient in DynamoDB than having an additional table instead.

A big assumption with this design I am making is that most users won't belong in many clubs whereas the reverse probably won't be true. And user information probably won't change much after registration so the repetition of user info won't be a big problem for us.

**Comment by srijonsaha** [comment]
Also if you guys are interested in how partition key and sort key word: https://docs.amazonaws.cn/en_us/amazondynamodb/latest/developerguide/HowItWorks.CoreComponents.html#HowItWorks.CoreComponents.PrimaryKey

**Comment by srijonsaha** [comment]
@bobheadxi I'm gonna experiment with how this will all work in Go once I have some time, but seems like option 3 is the way to go.

**Comment by bobheadxi** [comment]
This sounds good - my only concern is table updates, but this should work fine 👍

**Comment by leesw98** [comment]
@srijonsaha How would be handle the many to many relationship between club and user using the option 3? It seems unavoidable to store an array of ids or metadata. Thoughts?
